import fs from 'fs'
import path from 'path'

// Polyfills for pdf.js running in Node
if (typeof globalThis !== 'undefined') {
  if (!(globalThis as any).DOMMatrix) (globalThis as any).DOMMatrix = class DOMMatrix { }
  if (!(globalThis as any).Path2D) (globalThis as any).Path2D = class Path2D { }
  if (!(globalThis as any).ImageData) (globalThis as any).ImageData = class ImageData { }
}

const pdfParse = require('pdf-parse')

export type DocumentType = 'fir' | 'complaint' | 'statement' | 'summary'

const TEMPLATE_MAP: Record<DocumentType, string> = {
  fir: 'fir_template.pdf',
  complaint: 'police_complaint.pdf',
  statement: 'legal_statement.pdf',
  summary: 'case_summary.pdf',
}

export async function retrieveTemplate(type: DocumentType): Promise<string> {
  const filename = TEMPLATE_MAP[type]
  if (!filename) {
    throw new Error(`Invalid document type requested: ${type}`)
  }

  // Next.js standard path resolution (runs in Node environment)
  const templatePath = path.join(process.cwd(), 'lib', 'rag', 'templates', filename)

  if (!fs.existsSync(templatePath)) {
    console.warn(`Template file not found at: ${templatePath}. Using fallback template text.`)
    return getFallbackTemplate(type)
  }

  try {
    const dataBuffer = fs.readFileSync(templatePath)
    // pdf-parse extracts the text content
    try {
      const data = await pdfParse(dataBuffer)
      if (data && data.text) return data.text
    } catch (parseError) {
      console.warn(`pdf-parse failed on ${filename}, using robust static text fallback.`)
    }
    return getFallbackTemplate(type)
  } catch (error) {
    console.error(`Failed to parse PDF template ${filename} natively:`, error)
    return getFallbackTemplate(type)
  }
}

// Fallback registry matching the exact syntax generated in scripts/generate-templates.js
function getFallbackTemplate(type: DocumentType): string {
  const textRegistry: Record<DocumentType, string> = {
    fir: "FIRST INFORMATION REPORT (FIR)\n\n1. District: ______ P.S.: ______\n2. Date and time of occurrence: ______\n3. Name and residence of informant: ______\n4. Description of offense: \n\n[INJECT_GENERATED_CASE_DETAILS_HERE]\n\nSignature of Police Officer: __________",
    complaint: "FORMAL POLICE COMPLAINT\n\nTo,\nThe Station House Officer,\n[Jurisdiction]\n\nSubject: Criminal Complaint regarding [Incident_Type]\n\nSir/Madam,\nI am submitting this formal complaint based on the following verified timeline:\n\n[INJECT_GENERATED_CASE_DETAILS_HERE]\n\nKindly register this complaint. \n\nSignature: __________",
    statement: "LEGAL WITNESS/SURVIVOR STATEMENT\n\nUnder Section 161/164 legal formatting:\n\nStatement recorded concerning incidents:\n\n[INJECT_GENERATED_CASE_DETAILS_HERE]\n\nI affirm this timeline is factual and generated securely. \n\nDeponent: __________",
    summary: "JUSTICE FLOW - CASE SUMMARY DOSSIER\n\nEXECUTIVE OVERVIEW:\n\n[INJECT_GENERATED_CASE_DETAILS_HERE]\n\nGenerated by JusticeFlow AI Structure Engine."
  }
  return textRegistry[type]
}
